jokes = [
    {"name":"Abby", "punch":"Abby birthday to you!"},
    {"name":"Adam", "punch":"Adam up and tell me the total."},
    {"name":"Adolph", "punch":"Adolph ball hit me in de mowf."},
    {"name":"Adore", "punch":"Adore stands between us. Open up!"},
    {"name":"Ahmed", "punch":"Ahmed a big mistake coming here."},
    {"name":"Albie", "punch":"Albie darn, a funny joke!"},
    {"name":"Alex", "punch":"Alex-plain later."},
    {"name":"Alison", "punch":"Alison to you after you listen to me."},
    {"name":"Althea", "punch":"Althea later, Alligator!"},
    {"name":"Amanda", "punch":"Amanda fix the refrigerator is here."},
    {"name":"Ammonia", "punch":"Ammonia little kid."},
    {"name":"Amos", "punch":"A mosquito bit me."},
    {"name":"Andy", "punch":"And he bit me again!"},
    {"name":"Anita", "punch":"Anita ride to school."},
    {"name":"Anna", "punch":"Anna body know some more jokes?"},
    {"name":"Arthur", "punch":"Arthur more jokes here?"},
    {"name":"Ashley", "punch":"Ashley (actually!), I don't know."},
    {"name":"Bean", "punch":"Bean here for ages. What's kept you?"},
    {"name":"Beezer", "punch":"Beezer black and yellow and make honey."},
    {"name":"Before", "punch":"Before I freeze to death, please open the door!"},
    {"name":"Ben", "punch":"Been knocking so long my hand hurts!"},
    {"name":"Ben", "punch":"Ben knocking on this door all morning!"},
    {"name":"Boo", "punch":"Please don't cry. It's just a joke!"},
    {"name":"Candice", "punch":"Candice be the last knock-knock joke?"},
    {"name":"Candy", "punch":"Can Dee come out and play?"},
    {"name":"Canoe", "punch":"Canoe you lend me some money?"},
    {"name":"Carl", "punch":"Carl get you there quicker than if you walk."},
    {"name":"Cash", "punch":"I knew you were nuts!"},
    {"name":"Cash", "punch":"No thanks, but I'd like some peanuts!"},
    {"name":"Celeste", "punch":"Celeste time I'm telling you, open up."},
    {"name":"Champ", "punch":"Champ poo your hair, it's dirty."},
    {"name":"Claire", "punch":"Clear the way I'm coming in!"},
    {"name":"Colleen", "punch":"Colleen up your room, its a mess!"},
    {"name":"Conrad", "punch":"Conradulations, I used your joke!"},
    {"name":"Dawn", "punch":"Dawn by the station, early in the morning."},
    {"name":"Dewey", "punch":"Dewey have to keep saying all these jokes?"},
    {"name":"Dewey", "punch":"Dewey have to listen to all this knocking!"},
    {"name":"Diploma", "punch":"Diploma is here to fix the sink."},
    {"name":"Disco", "punch":"Disco-nnected"},
    {"name":"Disguise", "punch":"Disguise your boyfriend!"},
    {"name":"Don Juan", "punch":"Don Juan to go to shool today."},
    {"name":"Doris", "punch":"Doris locked that's why I am knocking!"},
    {"name":"Doris", "punch":"The Door is locked, that's why I'm knocking."},
    {"name":"Doughnut", "punch":"Doughnut worry it is just a joke!"},
    {"name":"Dozen", "punch":"Dozen anyone want to let me in?"},
    {"name":"Duane", "punch":"Duane the bathtub, I'm drowning!"},
    {"name":"Dwayne", "punch":"Dwayne the bathtub, I'm dwowning!"},
    {"name":"Eddie", "punch":"Eddie body home?"},
    {"name":"Eileen", "punch":"Eileen'd on your bell and broke it."},
    {"name":"Elsie", "punch":"Elsie you later."},
    {"name":"Emma", "punch":"Am ah cracking you up?"},
    {"name":"Enoch", "punch":"Enoch and Enoch but no one answers the door."},
    {"name":"Fannie", "punch":"Fannie body home?"},
    {"name":"Fanny", "punch":"These jokes aren't very fanny."},
    {"name":"Felix", "punch":"Felix my ice cream, I'll lick his!"},
    {"name":"Ferdie", "punch":"Ferdie last time, open up!"},
    {"name":"Formosa", "punch":"Formosa the summer I was away on my holiday."},
    {"name":"Frasier", "punch":"Frasier joke isn't very funny?"},
    {"name":"Freddie", "punch":"Freddie or not, here I come."},
    {"name":"General Lee", "punch":"Generally I do not tell jokes!"},
    {"name":"Genoa", "punch":"Genoa any new jokes?"},
    {"name":"Ghandi", "punch":"Ghandi cane"},
    {"name":"Ghost", "punch":"Ghost to show you don't remember my name!"},
    {"name":"Gladys", "punch":"Gladys is my last joke."},
    {"name":"Gorilla", "punch":"Gorilla me a cheese sandwich."},
    {"name":"Hair", "punch":"Hair today, gone tomorrow."},
    {"name":"Harriet", "punch":"Harriet up. We're going to be late."},
    {"name":"Harry", "punch":"Harry up and answer the door."},
    {"name":"Hawaii", "punch":"I'm fine. Hawaii you?"},
    {"name":"Holden", "punch":"Hold on, I'll go see."},
    {"name":"Howard", "punch":"Howard was the math test today?"},
    {"name":"Howie", "punch":"Howie going to figure this out?"},
    {"name":"Howl", "punch":"Howl you know unless you open the door!"},
    {"name":"Iam", "punch":"Sorry, I don't know who you are."},
    {"name":"Ice cream soda", "punch":"Ice cream soda whole world will know how much I love you!"},
    {"name":"Ida", "punch":"Ida know!"},
    {"name":"Ima", "punch":"Ima commin in, so open up."},
    {"name":"Ina", "punch":"Ina minute I'm going to knock this door down!"},
    {"name":"Irish", "punch":"Irish you would let me in."},
    {"name":"Isaac", "punch":"Isaac of knock-knock jokes!"},
    {"name":"Isabel", "punch":"Isabel not working?"},
    {"name":"Isabel", "punch":"Isabel out of order? I had to knock."},
    {"name":"Isadore", "punch":"Is a door needed on a toilet stall!"},
    {"name":"Isaiah", "punch":"Isaiah nothing till you open this door."},
    {"name":"Island", "punch":"Island on your roof with my parachute."},
    {"name":"Ivan", "punch":"Ivan workin on the railroad."},
    {"name":"Jamaica", "punch":"Jamaica mistake?"},
    {"name":"Jess", "punch":"Jess me, open the door."},
    {"name":"Juana", "punch":"Juana come out and play?"},
    {"name":"Justice", "punch":"Justice I thought. Nobody's home."},
    {"name":"Justin", "punch":"Justin time for dinner!"},
    {"name":"Justin", "punch":"Justin time for supper."},
    {"name":"Keith", "punch":"Keith me, thweet heart!"},
    {"name":"Ken", "punch":"Ken I come in? It's cold out here!"},
    {"name":"Ken", "punch":"Ken you tell me some good knock-knock jokes?"},
    {"name":"Kendall", "punch":"Kendall and Barbie go together."},
    {"name":"Kenya", "punch":"Kenya guess hwo it is?"},
    {"name":"Ketchup", "punch":"Ketchup with me an you'll find out!"},
    {"name":"Kip", "punch":"Kip your hands off of me!"},
    {"name":"Leaf", "punch":"Leaf me alone!"},
    {"name":"Lena", "punch":"Lena little closer and I'll tell you."},
    {"name":"Les", "punch":"Les hear another knock-knock joke!"},
    {"name":"Li'l ol'lady", "punch":"I didn't know you could yodel."},
    {"name":"Lionel", "punch":"Lionel bite you if you put your head in its mouth!"},
    {"name":"Luke", "punch":"Like through the keyhole and you'll see."},
    {"name":"Luke", "punch":"Luke out! Here comes another knock-knock joke."},
    {"name":"Lydia", "punch":"The lid a your trash can just blew off!"},
    {"name":"Mae", "punch":"Mae be i'll tell you and Mae be I won't."},
    {"name":"Manuel", "punch":"Manuel be sorry if you don't let him in."},
    {"name":"Marietta", "punch":"Marietta whole cake!"},
    {"name":"Marilyn", "punch":"Marilyn is a state just north of Virginia."},
    {"name":"Marsh", "punch":"Marshmallow!"},
    {"name":"Max", "punch":"Max no difference to you, just let me in."},
    {"name":"Mikey", "punch":"Mikey won't fit in this lock."},
    {"name":"Nadia", "punch":"Nadia head if you understand what I'm saying."},
    {"name":"Needle", "punch":"Needle little more time."},
    {"name":"Noah", "punch":"Noah don't know who you are either!"},
    {"name":"Noah", "punch":"Noah good place to find more jokes?"},
    {"name":"Norma Lee", "punch":"Norma Lee I don't go around knocking on people's doors, but I just had to meet you."},
    {"name":"Norma Lee", "punch":"Normally I ring the doorbell!"},
    {"name":"Norway", "punch":"Norway will I leave till you open this door!"},
    {"name":"Nuisance", "punch":"Any nuisance I saw you yesterday?"},
    {"name":"Olive", "punch":"Olive right next door to you."},
    {"name":"Olive", "punch":"Olive you!"},
    {"name":"Oliver", "punch":"Oliver you there are bugs!"},
    {"name":"Orange", "punch":"Orange you going to open this door?"},
    {"name":"Ozzie", "punch":"Ozzie you later."},
    {"name":"Pecan", "punch":"Pecan me again and I'll tell the teacher!"},
    {"name":"Phillip", "punch":"Phillip my glass, will you please?"},
    {"name":"Phillip", "punch":"Phillip the gas tank, I'm running low."},
    {"name":"Phyllis", "punch":"Phyllis in on the news, please."},
    {"name":"Quack", "punch":"Quack another bad joke and I'm leaving."},
    {"name":"Qualify", "punch":"I'll qualify ever want to tell you."},
    {"name":"Quarter", "punch":"Quarter with her hand in the cookie jar!"},
    {"name":"Quebec", "punch":"Quebec to the end of the line!"},
    {"name":"Quilt", "punch":"Quilt-ee as charged."},
    {"name":"Raleigh", "punch":"Raleigh `round the flag, boys!"},
    {"name":"Reed", "punch":"Reed between the lines."},
    {"name":"Rhoda", "punch":"Rhoda horse yesterday and fell off."},
    {"name":"Rosa", "punch":"Rosa corn grow in the field."},
    {"name":"Rufus", "punch":"Rufus leaking and I'm getting wet!"},
    {"name":"Rufus", "punch":"Your roof is on fire!"},
    {"name":"Sadie", "punch":"Sadie magic words and I'll tell you."},
    {"name":"Safari", "punch":"Safari, so good."},
    {"name":"Sally", "punch":"Sally-brate the moments of your life!"},
    {"name":"Sam", "punch":"Sam person who knocked on the door last time!"},
    {"name":"Sarah", "punch":"Sarah doctor in the house?"},
    {"name":"Sarah", "punch":"Sarah reason you're not laughing?"},
    {"name":"Shirley", "punch":"Shirley you must know me by now?"},
    {"name":"Stan", "punch":"Stan back, I think I'm going to sneeze!"},
    {"name":"Surely", "punch":"Surely you can open the door!"},
    {"name":"Tank", "punch":"You're welcome!"},
    {"name":"Tennis", "punch":"Tennis five plus five."},
    {"name":"Thatcher", "punch":"Thatcher was a funny joke!"},
    {"name":"Thea", "punch":"Thea later, alligator!"},
    {"name":"Theodore", "punch":"Open Theodore an let me in."},
    {"name":"Theodore", "punch":"Theodore wasn't open so I knocked!"},
    {"name":"Thermos", "punch":"Thermos be a better knock-knock joke than this!"},
    {"name":"Tinker Bell", "punch":"Tinker Bell is out of order."},
    {"name":"Toby", "punch":"To be, or not to be. That is the question!"},
    {"name":"Tom Sawyer", "punch":"Tom saw yer underwear!"},
    {"name":"Tuna", "punch":"Tuna piano and it will sound better."},
    {"name":"Udder", "punch":"Udder people let me in, why don't you?"},
    {"name":"Uganda", "punch":"Uganda get away with this!"},
    {"name":"Uriah", "punch":"Kepp Uriah on the ball!"},
    {"name":"Usher", "punch":"Usher wish you would let me in."},
    {"name":"Utta", "punch":"Utta sight, Utta mind."},
    {"name":"Van", "punch":"Van can I see you again?"},
    {"name":"Vaughn", "punch":"Vaughn day my prince will come."},
    {"name":"Venice", "punch":"Venice your mother coming home?"},
    {"name":"Vera", "punch":"Vera few people think these jokes are funny."},
    {"name":"Verdi", "punch":"Verdi been all day?"},
    {"name":"Vida", "punch":"Vida you talk like that!"},
    {"name":"Viola", "punch":"Viola sudden don't you know me?"},
    {"name":"Violet", "punch":"Violet the cat out of the bag?"},
    {"name":"Voodoo", "punch":"Voodoo you think you are?"},
    {"name":"Voodoo", "punch":"Voodoo you think you are?"},
    {"name":"Waddle", "punch":"Waddle you give me if I go away?"},
    {"name":"Wade", "punch":"Wade down upon the river."},
    {"name":"Wah", "punch":"Gee, I didn't know you'd get so excited about it!"},
    {"name":"Wanda", "punch":"Wanda where I put my car keys!"},
    {"name":"Warrior", "punch":"Warrior been all my life?"},
    {"name":"Watson", "punch":"Watson TV tonight?"},
    {"name":"Wayne", "punch":"Wayne, Wayne, go away, come again another day!"},
    {"name":"Wendy", "punch":"Wendy last time you took a bath?"},
    {"name":"Wendy", "punch":"Wendy the last time you took a bath?"},
    {"name":"Who", "punch":"Did you hear an owl?"},
    {"name":"Will", "punch":"Will you let me in, its cold out here."},
    {"name":"X", "punch":"X for breakfast."},
    {"name":"Xavier", "punch":"Xavier breath, I'm not leaving!"},
    {"name":"Xavier", "punch":"Xavier money for a rainy day."},
    {"name":"Xenia", "punch":"Xenia playing ball at the park."},
    {"name":"Ya", "punch":"I didn't know you were a cowboy!"},
    {"name":"Yacht", "punch":"Yacht a know me by now!"},
    {"name":"Yellow", "punch":"Yellow my name is Katie."},
    {"name":"Yolanda", "punch":"Yolanda me some money?"},
    {"name":"You", "punch":"Did you call me?"},
    {"name":"Zany", "punch":"Zany body home?"},
    {"name":"Zeke", "punch":"Zeke and you shall find!"},
    {"name":"Zippy", "punch":"Mrs. Zippy"},
    {"name":"Zizi", "punch":"Zizi when you know how."},
    {"name":"Zone", "punch":"Zone dog bit him in the leg!"},
    {"name":"Catsup", "punch":"Catsup a tree and she won't come down!"},
    {"name":"Claws", "punch":"Claws the door behind us!"},
    {"name":"Arthur", "punch":"Arthur any more dogs out there?"},
    {"name":"Ken", "punch":"Ken I bring my dog inside?"},
    {"name":"Whale", "punch":"Whale will you let me in or won't you?"},
    {"name":"Alpaca", "punch":"Alpaca the trunk, you pack-a the suitcase."},
    {"name":"Lion", "punch":"I'm lion on your doorstep, ipen up!"},
    {"name":"Goat", "punch":"Goat to the door and find out."},
    {"name":"Aware", "punch":"Aware, aware have my little sheep gone?"},
    {"name":"Snakeskin", "punch":"Snakes-kin bite, but we'd rather run away."},
    {"name":"Ants", "punch":"Ants in your pants will make you dance."},
    {"name":"Honeybee", "punch":"Honeybee a dear and get me a glass of beer."},
    {"name":"Icy", "punch":"Icy a polar bear up ahead."},
    {"name":"Berry", "punch":"Berry nice to meet you!"},
    {"name":"Eye", "punch":"Eye know you took a bite out of my apple!"},
    {"name":"Ben", "punch":"Ben out picking apples."},
    {"name":"Water", "punch":"Water you doing with my hot chocolate?"},
    {"name":"Butter", "punch":"Butter let me in!"},
    {"name":"Ham", "punch":"Ham and eggs for breakfast."},
    {"name":"Beehive", "punch":"Beehive yourself or you'll get in trouble!"},
    {"name":"Bee", "punch":"Bee nice and let me in."},
    {"name":"Wheel", "punch":"Wheel you share an ice cream with me?"},
    {"name":"Radio", "punch":"Redio not, here I come!"},
    {"name":"Wood", "punch":"Wood you be quiet?"},
    {"name":"Randy", "punch":"Randy mile in under four minutes."}
]
